# Lesson 10 activity solution

## Learning objectives

By the end of this activity, you will be able to:
- Create Pandas Series and DataFrames
- Load data from CSV files
- Perform basic data exploration and analysis
- Calculate descriptive statistics
- Filter and manipulate DataFrame data

## Tips

- **Creating DataFrames:** Use `pd.DataFrame(dictionary)` where dictionary keys become column names
- **Loading CSV files:** Use `pd.read_csv('filename.csv')`
- **Basic exploration:** Use `.head()`, `.tail()`, `.info()`, `.describe()`, and `.shape`
- **Filtering data:** Use conditions like `df[df['column'] > value]`
- **Column selection:** Use `df['column_name']` or `df[['col1', 'col2']]`
- **Adding columns:** Use `df['new_column'] = calculation`
- **Statistics:** Use `.mean()`, `.max()`, `.min()`, `.sum()` methods

**Remember:** Take your time with each step and test your code frequently!

In [1]:
import pandas as pd

---
## Problem 1: creating your first DataFrame

**Scenario:** You're working at a bookstore and need to create a simple inventory system.

**Your Task:**
1. Create a DataFrame called `books_df` with the following data:
   - Book titles: ["Python Basics", "Data Science Handbook", "Web Development Guide"]
   - Authors: ["John Smith", "Jane Doe", "Mike Johnson"]
   - Prices: [29.99, 45.50, 35.00]
   - Stock: [15, 8, 12]

2. Display the DataFrame
3. Print the shape of the DataFrame
4. Display basic information about the DataFrame using `.info()`

In [2]:
# Step 1: Create the DataFrame
books_df = pd.DataFrame({
    'title': ['Python Basics', 'Data Science Handbook', 'Web Development Guide'],
    'author': ['John Smith', 'Jane Doe', 'Mike Johnson'],
    'price': [29.99, 45.50, 35.00],
    'stock': [15, 8, 12]
})

In [3]:
# Step 2: Display the DataFrame
print('Books DataFrame:')
books_df

Books DataFrame:

                   title        author  price  stock
0          Python Basics    John Smith  29.99     15
1  Data Science Handbook      Jane Doe  45.50      8
2  Web Development Guide  Mike Johnson  35.00     12

In [4]:
# Step 3: Print the shape
print(f'Shape of DataFrame: {books_df.shape}')
print(f'This means: {books_df.shape[0]} rows and {books_df.shape[1]} columns')

Shape of DataFrame: (3, 4)
This means: 3 rows and 4 columns

In [5]:
# Step 4: Display info
print('DataFrame Information:')
books_df.info()

DataFrame Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   title   3 non-null      object
 1   author  3 non-null      object
 2   price   3 non-null      float64
 3   stock   3 non-null      int64
dtypes: float64(1), int64(1), object(2)
memory usage: 228.0+ bytes

---
## Problem 2: loading and exploring data

**Scenario:** You're a teacher analyzing student performance data.

**Your Task:**
1. Load the `students.csv` file into a DataFrame called `students_df`
2. Display the first 3 rows using `.head()`
3. Display the last 2 rows using `.tail()`
4. Show descriptive statistics for numerical columns using `.describe()`
5. Find the average grade of all students

Students data file avalible for download here: [students.csv](https://media.githubusercontent.com/media/gperdrizet/fullstack-2605/refs/heads/main/data/students.csv)

In [ ]:
# Step 1: Load the CSV file
url = 'https://media.githubusercontent.com/media/gperdrizet/fullstack-2605/refs/heads/main/data/students.csv'
students_df = pd.read_csv(url)
print('Students data loaded successfully!')

Students data loaded successfully!

In [7]:
# Step 2: Display first 3 rows
print('First 3 rows:')
students_df.head(3)

First 3 rows:

      name  age  grade  subject
0    Alice   20     85     Math
1      Bob   19     92  Science
2  Charlie   21     78     Math

In [8]:
# Step 3: Display last 2 rows
print('Last 2 rows:')
students_df.tail(2)

Last 2 rows:

    name  age  grade  subject
6  Grace   20     90     Math
7  Henry   21     87  Science

In [9]:
# Step 4: Show descriptive statistics
print('Descriptive Statistics:')
students_df.describe()

Descriptive Statistics:

             age      grade
count   8.000000   8.000000
mean   20.250000  87.125000
std     1.035098   5.462535
min    19.000000  78.000000
25%    19.750000  84.250000
50%    20.000000  87.500000
75%    21.000000  90.500000
max    22.000000  95.000000

In [10]:
# Step 5: Calculate average grade
average_grade = students_df['grade'].mean()
print(f'Average grade of all students: {average_grade:.2f}')

Average grade of all students: 87.12

---
## Problem 3: data filtering and selection

**Scenario:** Continue working with the student data to find specific information.

**Your Task:**
1. Display only the 'name' and 'grade' columns from `students_df`
2. Find all students who scored above 85
3. Find all students studying 'Math'
4. Find the highest grade in the dataset
5. Count how many students are in each subject

In [11]:
# Step 1: Display only name and grade columns
print('Name and Grade columns:')
grade_df = students_df[['name', 'grade']]
grade_df

Name and Grade columns:

      name  grade
0    Alice     85
1      Bob     92
2  Charlie     78
3    Diana     88
4      Eva     95
5    Frank     82
6    Grace     90
7    Henry     87

In [12]:
# Step 2: Students with grades above 85
print('Students with grades above 85:')
high_performers_df = students_df[students_df['grade'] > 85]
high_performers_df

Students with grades above 85:

    name  age  grade  subject
1    Bob   19     92  Science
3  Diana   20     88  Science
4    Eva   19     95     Math
6  Grace   20     90     Math
7  Henry   21     87  Science

In [13]:
# Step 3: Students studying Math
print('Students studying Math:')
math_students_df = students_df[students_df['subject'] == 'Math']
math_students_df

Students studying Math:

      name  age  grade subject
0    Alice   20     85    Math
2  Charlie   21     78    Math
4      Eva   19     95    Math
6    Grace   20     90    Math

In [14]:
# Step 4: Highest grade
highest_grade = students_df['grade'].max()
print(f'Highest grade: {highest_grade}')

Highest grade: 95

In [15]:
# Step 5: Count students by subject
print('Number of students in each subject:')
subject_counts = students_df['subject'].value_counts()
subject_counts

Number of students in each subject:

subject
Math       4
Science    4
Name: count, dtype: int64

---
## Problem 4: sales data analysis

**Scenario:** You're analyzing sales data for an electronics store.

**Your Task:**
1. Load the `sales.csv` file into a DataFrame called `sales_df`
2. Calculate the total value for each product (price × quantity)
3. Add this as a new column called 'total_value' to the DataFrame
4. Find the product with the highest total value
5. Calculate the grand total of all sales

Sales data file avalible for download here: [sales.csv](https://media.githubusercontent.com/media/gperdrizet/fullstack-2605/refs/heads/main/data/sales.csv)

In [ ]:
# Step 1: Load the sales data
url = 'https://media.githubusercontent.com/media/gperdrizet/fullstack-2605/refs/heads/main/data/sales.csv'
sales_df = pd.read_csv(url)
print('Sales data loaded:')
sales_df

Sales data loaded:

      product   price  quantity        date
0      Laptop  999.99         5  2024-01-15
1       Mouse   25.50        20  2024-01-15
2    Keyboard   75.00        15  2024-01-16
3     Monitor  299.99         8  2024-01-16
4  Headphones   59.99        12  2024-01-17

In [17]:
# Step 2 & 3: Calculate total value and add as new column
sales_df['total_value'] = sales_df['price'] * sales_df['quantity']
print('Sales data with total_value column:')
sales_df

Sales data with total_value column:

      product   price  quantity        date  total_value
0      Laptop  999.99         5  2024-01-15      4999.95
1       Mouse   25.50        20  2024-01-15       510.00
2    Keyboard   75.00        15  2024-01-16      1125.00
3     Monitor  299.99         8  2024-01-16      2399.92
4  Headphones   59.99        12  2024-01-17       719.88

In [18]:
# Step 4: Find product with highest total value
max_value_idx = sales_df['total_value'].idxmax()
top_product = sales_df.loc[max_value_idx]
print(f'Product with highest total value:')
print(f'Product: {top_product['product']}')
print(f'Total Value: ${top_product['total_value']:.2f}')

Product with highest total value:
Product: Laptop
Total Value: $4999.95

In [19]:
# Alternative method for Step 4:
top_product_row = sales_df[sales_df['total_value'] == sales_df['total_value'].max()]
top_product_row

  product   price  quantity        date  total_value
0  Laptop  999.99         5  2024-01-15      4999.95

In [20]:
# Step 5: Calculate grand total of all sales
grand_total = sales_df['total_value'].sum()
print(f'Grand total of all sales: ${grand_total:.2f}')

Grand total of all sales: $9754.75

---
## Problem 5: series creation and manipulation

**Scenario:** Create and work with Pandas Series for daily temperature data.

**Your Task:**
1. Create a Pandas Series called `temperatures` with the following data:
   - Values: [22, 25, 23, 26, 24, 27, 25]
   - Index: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
2. Find the temperature for Wednesday
3. Find days with temperature above 24 degrees
4. Calculate the average temperature for the week
5. Find the day with the highest temperature

In [21]:
# Step 1: Create the temperature series
temperatures = pd.Series(
    [22, 25, 23, 26, 24, 27, 25],
    index=['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
    name='Temperature (°C)'
)
print('Temperature Series:')
temperatures

Temperature Series:

Mon    22
Tue    25
Wed    23
Thu    26
Fri    24
Sat    27
Sun    25
Name: Temperature (°C), dtype: int64

In [22]:
# Step 2: Temperature for Wednesday
wed_temp = temperatures['Wed']
print(f'Temperature on Wednesday: {wed_temp}°C')

Temperature on Wednesday: 23°C

In [23]:
# Step 3: Days with temperature above 24
hot_days = temperatures[temperatures > 24]
print('Days with temperature above 24°C:')
print(hot_days)

Days with temperature above 24°C:
Tue    25
Thu    26
Sat    27
Sun    25
Name: Temperature (°C), dtype: int64

In [24]:
# Step 4: Average temperature
avg_temp = temperatures.mean()
print(f'Average temperature for the week: {avg_temp:.1f}°C')

Average temperature for the week: 24.6°C

In [25]:
# Step 5: Day with highest temperature
hottest_day = temperatures.idxmax()
hottest_temp = temperatures.max()
print(f'Hottest day: {hottest_day} with {hottest_temp}°C')

Hottest day: Sat with 27°C

---
## Reflection questions

**1. What is the difference between a Pandas Series and a DataFrame?**

*Sample answer:* A Pandas Series is a one-dimensional labeled array that can hold any data type (like a single column). A DataFrame is a two-dimensional labeled data structure with rows and columns (like a table or spreadsheet). You can think of a DataFrame as a collection of Series objects that share the same index. Each column in a DataFrame is essentially a Series.

**2. What are the advantages of using Pandas over working with plain Python lists and dictionaries?**

*Sample answer:* Pandas offers several advantages:
- **Labeled data:** Rows and columns have meaningful names, making data easier to understand
- **Built-in operations:** Methods like `.mean()`, `.describe()`, `.filter()` are optimized and easy to use
- **Handling missing data:** Pandas has tools to detect and handle missing values
- **Easy data import/export:** Simple functions to read/write CSV, Excel, SQL databases, etc.
- **Performance:** Built on NumPy, so it's much faster for large datasets
- **Data alignment:** Automatically aligns data based on labels when performing operations

**3. Describe a real-world scenario where you might use the filtering techniques you learned in Problem 3.**

*Sample answer:* In an e-commerce business, I might use filtering to:
- Find all orders above $100 for premium customer analysis
- Filter products by category to analyze sales by department
- Identify customers who haven't made a purchase in 90 days for targeted marketing
- Find all transactions from a specific date range for monthly reports
- Filter inventory items with stock below a threshold to trigger reordering

**4. What did you find most challenging about working with Pandas in this activity?**

*Sample answer:* Understanding the difference between single and double brackets for column selection was initially confusing. `df['column']` returns a Series, while `df[['column']]` returns a DataFrame. Also, remembering when to use `.loc[]` vs `.iloc[]` vs direct indexing took some practice. The boolean filtering syntax with nested brackets like `df[df['column'] > value]` also required careful attention to get right.