# Lesson 10 demo: Pandas

## 1. Set up

Install with:

```text
pip install pandas
```

In [1]:
import pandas as pd
print(f'Pandas version {pd.__version__}')

Pandas version 1.5.3

## 1. Series: one-dimensional data

### 1.1. Create a series

In [2]:
my_series = pd.Series([20, 30, 40, 50])
print(my_series)

0    20
1    30
2    40
3    50
dtype: int64

In [3]:
type(my_series)

pandas.core.series.Series

In [4]:
day = ['Mon', 'Tues', 'Wed', 'Thurs']
print(day)

['Mon', 'Tues', 'Wed', 'Thurs']

In [5]:
my_indexed_series = pd.Series([20, 30, 40, 50], index=day)
print(my_indexed_series)

Mon      20
Tues     30
Wed      40
Thurs    50
dtype: int64

### 1.2. Indexing series

In [6]:
print(my_indexed_series['Wed'])

40

In [7]:
print(my_series.iloc[1])

30

### 2.3. Series operations

In [8]:
print(my_series.max())

50

In [9]:
print(my_series.mean())

35.0

## 2. DataFrame: two-deimensional data

### 2.1. Creating dataframes

In [10]:
data = {
    'name': ['Alice', 'Bob', 'Laura', 'George'],
    'age': [25, 30, 35, 40],
    'city': ['New York', 'Paris', 'London', 'Chicago'],
    'salary': [50000, 60000, 70000, 80000]
}

type(data)

dict

In [11]:
print(data)

{'name': ['Alice', 'Bob', 'Laura', 'George'], 'age': [25, 30, 35, 40], 'city': ['New York', 'Paris', 'London', 'Chicago'], 'salary': [50000, 60000, 70000, 80000]}

In [12]:
df = pd.DataFrame(data)
df

     name  age      city  salary
0   Alice   25  New York   50000
1     Bob   30     Paris   60000
2   Laura   35    London   70000
3  George   40   Chicago   80000

In [15]:
weather_df = pd.read_csv('./Weather_data.csv')
weather_df.head(10)

   Day  Temperature  Precipitation
0    1    23.232203       2.645556
1    2    25.727840       7.742337
2    3    24.041451       4.561503
3    4    23.173248       5.684339
4    5    21.354822       0.187898
5    6    24.688412       6.176355
6    7    21.563808       6.120957
7    8    28.376595       6.169340
8    9    29.454941       9.437481
9   10    20.751623       6.818203

### 2.2. Setting the index

In [46]:
new_index = ['a', 'b', 'c', 'd']
df.set_index(pd.Index(new_index), inplace=True)

In [47]:
df['index_col'] = new_index

In [48]:
df

     name  age      city  salary index_col
a   Alice   25  New York   50000         a
b     Bob   30     Paris   60000         b
c   Laura   35    London   70000         c
d  George   40   Chicago   80000         d

In [50]:
df.drop('index_col', axis=1, inplace=True)
df

     name  age      city  salary
a   Alice   25  New York   50000
b     Bob   30     Paris   60000
c   Laura   35    London   70000
d  George   40   Chicago   80000

In [51]:
df.reset_index(inplace=True, drop=True)
df

     name  age      city  salary
0   Alice   25  New York   50000
1     Bob   30     Paris   60000
2   Laura   35    London   70000
3  George   40   Chicago   80000

### 2.3. Getting and setting column names

In [52]:
col_names = df.columns

In [53]:
print(col_names)

Index(['name', 'age', 'city', 'salary'], dtype='object')

In [54]:
rename_dict = {'city': 'location'}

In [55]:
df.rename(columns=rename_dict, inplace=True)
df

     name  age  location  salary
0   Alice   25  New York   50000
1     Bob   30     Paris   60000
2   Laura   35    London   70000
3  George   40   Chicago   80000

In [61]:
df.column = pd.Index(['Name', 'Age', 'City', 'Salary'])
df

     name  age  location  salary
0   Alice   25  New York   50000
1     Bob   30     Paris   60000
2   Laura   35    London   70000
3  George   40   Chicago   80000

### 2.4. Getting information about dataframe

In [62]:
df.head(2)

    name  age  location  salary
0  Alice   25  New York   50000
1    Bob   30     Paris   60000

In [63]:
df.tail(3)

     name  age location  salary
1     Bob   30    Paris   60000
2   Laura   35   London   70000
3  George   40  Chicago   80000

In [64]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   name      4 non-null      object
 1   age       4 non-null      int64
 2   location  4 non-null      object
 3   salary    4 non-null      int64
dtypes: int64(2), object(2)
memory usage: 256.0+ bytes

In [65]:
df.describe()

             age        salary
count   4.000000      4.000000
mean   32.500000  65000.000000
std     6.454972  12909.944487
min    25.000000  50000.000000
25%    28.750000  57500.000000
50%    32.500000  65000.000000
75%    36.250000  72500.000000
max    40.000000  80000.000000

### 2.5. Selecting data

In [19]:
name_col = df['name']
name_col

0     Alice
1       Bob
2     Laura
3    George
Name: name, dtype: object

In [23]:
cols = ['name', 'age']

multiple_col = df[cols]
multiple_col

     name  age
0   Alice   25
1     Bob   30
2   Laura   35
3  George   40

In [27]:
index = pd.Index(['first', 'second', 'third', 'fourth'])

df.set_index(index, inplace=True)
df

          name  age      city  salary
first    Alice   25  New York   50000
second     Bob   30     Paris   60000
third    Laura   35    London   70000
fourth  George   40   Chicago   80000

In [28]:
df.loc['first']

name         Alice
age             25
city      New York
salary       50000
Name: first, dtype: object

In [31]:
df.iloc[0]

name         Alice
age             25
city      New York
salary       50000
Name: first, dtype: object

In [32]:
df.loc[['first', 'second']]

         name  age      city  salary
first   Alice   25  New York   50000
second    Bob   30     Paris   60000

In [33]:
df.loc[['first', 'second'], ['name', 'city']]

         name      city
first   Alice  New York
second    Bob     Paris

In [34]:
df.iloc[:, 1:3]

        age      city
first    25  New York
second   30     Paris
third    35    London
fourth   40   Chicago

### 2.6. Filtering

In [35]:
df['salary'] > 60000

first     False
second    False
third      True
fourth     True
Name: salary, dtype: bool

In [36]:
df[df['salary'] > 60000]

          name  age     city  salary
third    Laura   35   London   70000
fourth  George   40  Chicago   80000

In [37]:
df[df['city'] == 'London']

        name  age    city  salary
third  Laura   35  London   70000

## 3. Working with dates

### 3.1. Creating datetime data

In [38]:
dates = pd.to_datetime(['2026-01-01', '2026-02-01', '2026-03-01', '2026-02-01'])
dates

DatetimeIndex(['2026-01-01', '2026-02-01', '2026-03-01', '2026-02-01'], dtype='datetime64[ns]', freq=None)

In [39]:
df_dates = pd.DataFrame({
    'event': ['New Year', 'Valentine', 'Spring', 'July 4th'],
    'date': pd.to_datetime(['2026-01-01', '2026-02-15', '2026-03-20', '2026-07-04'])
})
df_dates

       event       date
0   New Year 2026-01-01
1  Valentine 2026-02-15
2     Spring 2026-03-20
3   July 4th 2026-07-04

In [40]:
df_dates.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   event   4 non-null      object
 1   date    4 non-null      datetime64[ns]
dtypes: datetime64[ns](1), object(1)
memory usage: 192.0+ bytes

In [41]:
df_dates['year'] = df_dates['date'].dt.year
df_dates

       event       date  year
0   New Year 2026-01-01  2026
1  Valentine 2026-02-15  2026
2     Spring 2026-03-20  2026
3   July 4th 2026-07-04  2026

In [42]:
df_dates['month'] = df_dates['date'].dt.month
df_dates

       event       date  year  month
0   New Year 2026-01-01  2026      1
1  Valentine 2026-02-15  2026      2
2     Spring 2026-03-20  2026      3
3   July 4th 2026-07-04  2026      7

In [43]:
df_dates['day'] = df_dates['date'].dt.day
df_dates

       event       date  year  month  day
0   New Year 2026-01-01  2026      1    1
1  Valentine 2026-02-15  2026      2   15
2     Spring 2026-03-20  2026      3   20
3   July 4th 2026-07-04  2026      7    4

### 3.3. Date arithmetic

In [44]:
days_since_newyear = (df_dates['date'] - df_dates['date'].min()).dt.days
df_dates['days_since_newyear'] = days_since_newyear
df_dates

       event       date  year  month  day  days_since_newyear
0   New Year 2026-01-01  2026      1    1                   0
1  Valentine 2026-02-15  2026      2   15                  45
2     Spring 2026-03-20  2026      3   20                  78
3   July 4th 2026-07-04  2026      7    4                 184

## 4. Working with data types

In [45]:
mixed_data = pd.DataFrame({
    'numbers_as_text': ['1', '2', '3', '4', '5'],
    'prices': ['10.50', '20.75', '15.25', '30.00', '25.50'],
    'categories': ['A', 'B', 'A', 'C', 'B'],
    'is_active': ['True', 'False', 'True', 'True', 'False'],
    'dates_as_text': ['2024-01-01', '2024-01-02', '2024-01-03', '2024-01-04', '2024-01-05']
})
mixed_data

  numbers_as_text prices categories is_active dates_as_text
0               1  10.50          A      True    2024-01-01
1               2  20.75          B     False    2024-01-02
2               3  15.25          A      True    2024-01-03
3               4  30.00          C      True    2024-01-04
4               5  25.50          B     False    2024-01-05

In [46]:
mixed_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   numbers_as_text  5 non-null      object
 1   prices           5 non-null      object
 2   categories       5 non-null      object
 3   is_active        5 non-null      object
 4   dates_as_text    5 non-null      object
dtypes: object(5)
memory usage: 328.0+ bytes

In [48]:
mixed_data['prices'] = mixed_data['prices'].astype(float)
mixed_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   numbers_as_text  5 non-null      object
 1   prices           5 non-null      float64
 2   categories       5 non-null      object
 3   is_active        5 non-null      object
 4   dates_as_text    5 non-null      object
dtypes: float64(1), object(4)
memory usage: 328.0+ bytes

In [49]:
mixed_data['categories'] = mixed_data['categories'].astype('category')
mixed_data

  numbers_as_text  prices categories is_active dates_as_text
0               1   10.50          A      True    2024-01-01
1               2   20.75          B     False    2024-01-02
2               3   15.25          A      True    2024-01-03
3               4   30.00          C      True    2024-01-04
4               5   25.50          B     False    2024-01-05

In [50]:
mixed_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   numbers_as_text  5 non-null      object
 1   prices           5 non-null      float64
 2   categories       5 non-null      category
 3   is_active        5 non-null      object
 4   dates_as_text    5 non-null      object
dtypes: category(1), float64(1), object(3)
memory usage: 425.0+ bytes

In [51]:
mixed_data['categories'].cat.categories

Index(['A', 'B', 'C'], dtype='object')

In [52]:
mixed_data['dates_as_text'] = mixed_data['dates_as_text'].astype('string')

In [53]:
mixed_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   numbers_as_text  5 non-null      object
 1   prices           5 non-null      float64
 2   categories       5 non-null      category
 3   is_active        5 non-null      object
 4   dates_as_text    5 non-null      string
dtypes: category(1), float64(1), object(2), string(1)
memory usage: 425.0+ bytes

## 5. Iteration

In [56]:
for index, row in df.iterrows():
    print(f'{index} row, name: {row["name"]}')

first row, name: Alice
second row, name: Bob
third row, name: Laura
fourth row, name: George

In [58]:
count = 0

while count < len(df):
    print(f'{df.iloc[count]}')
    count+=1

name         Alice
age             25
city      New York
salary       50000
Name: first, dtype: object
name        Bob
age          30
city      Paris
salary    60000
Name: second, dtype: object
name       Laura
age           35
city      London
salary     70000
Name: third, dtype: object
name       George
age            40
city      Chicago
salary      80000
Name: fourth, dtype: object

## 6. Sorting

In [61]:
df.sort_values('age')

          name  age      city  salary
first    Alice   25  New York   50000
second     Bob   30     Paris   60000
third    Laura   35    London   70000
fourth  George   40   Chicago   80000

In [62]:
df.sort_values('age', ascending=False)

          name  age      city  salary
fourth  George   40   Chicago   80000
third    Laura   35    London   70000
second     Bob   30     Paris   60000
first    Alice   25  New York   50000

In [64]:
df.sort_values(['age', 'city'])

          name  age      city  salary
first    Alice   25  New York   50000
second     Bob   30     Paris   60000
third    Laura   35    London   70000
fourth  George   40   Chicago   80000

## 7. `apply()` and `groupby()`

### 7.1 `apply()`

In [66]:
def double(x):
    print(f'Doubling {x}')
    return x * 2

In [67]:
print(double(5))

Doubling 5
10

In [68]:
double_lambda = lambda x: x * 2
print(double_lambda(5))

10

In [72]:
df['salary'] = df['salary'].apply(lambda x: x * 1.1)
df

          name  age      city   salary
first    Alice   25  New York  60500.0
second     Bob   30     Paris  72600.0
third    Laura   35    London  84700.0
fourth  George   40   Chicago  96800.0

In [77]:
def salary_bracket(salary):
    
    if salary >= 80000:
        return 'high'
    
    elif salary >= 50000:
        return 'mid'
    
    else:
        return 'standard'

In [78]:
df['bracket'] = df['salary'].apply(salary_bracket)
df

          name  age      city   salary bracket
first    Alice   25  New York  60500.0     mid
second     Bob   30     Paris  72600.0     mid
third    Laura   35    London  84700.0    high
fourth  George   40   Chicago  96800.0    high

### 7.2. `groupby()`

In [82]:
sales = pd.DataFrame({
    'region': ['North', 'South', 'North', 'South', 'East'],
    'product': ['A', 'A', 'B', 'B', 'A'],
    'revenue': [100, 150, 200, 130, 110]
})

sales

  region product  revenue
0  North       A      100
1  South       A      150
2  North       B      200
3  South       B      130
4   East       A      110

In [83]:
sales.groupby('region')['revenue'].sum()

region
East     110
North    300
South    280
Name: revenue, dtype: int64

In [84]:
sales.groupby(['region', 'product'])['revenue'].sum()

region  product
East    A          110
North   A          100
        B          200
South   A          150
        B          130
Name: revenue, dtype: int64

In [85]:
sales.groupby('region')['revenue'].agg(['min', 'max', 'sum', 'mean'])

        min  max  sum   mean
region
East    110  110  110  110.0
North   100  200  300  150.0
South   130  150  280  140.0

## 8. Writing to a file

In [87]:
sales.to_json('./sales_data.json')

In [88]:
sales_json = pd.read_json('./sales_data.json')
sales_json

  region product  revenue
0  North       A      100
1  South       A      150
2  North       B      200
3  South       B      130
4   East       A      110

In [89]:
sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   region   5 non-null      object
 1   product  5 non-null      object
 2   revenue  5 non-null      int64
dtypes: int64(1), object(2)
memory usage: 248.0+ bytes

In [90]:
sales_json.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   region   5 non-null      object
 1   product  5 non-null      object
 2   revenue  5 non-null      int64
dtypes: int64(1), object(2)
memory usage: 160.0+ bytes